#
# Copyright (C) 2021 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
orbs:
  win: circleci/windows@2.0.0
commands:

  install-bazel-mac:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/vaticle/dependencies/master/tool/bazelinstall/mac.sh
      - run: bash ./mac.sh && rm ./mac.sh

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: bazel run @vaticle_dependencies//tool/bazelrun:rbe -- << parameters.command >>
          no_output_timeout: 120m

jobs:
  deploy-mac-and-brew:
    macos:
      xcode: "12.5.1"
    working_directory: ~/typedb-workbase
    steps:
      - install-bazel-mac
      - checkout
      - run: |
          echo "Creating release notes..."
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @vaticle_dependencies//tool/release:create-notes -- typedb-workbase $(cat VERSION) ./RELEASE_TEMPLATE.md
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          echo "Deploying to GitHub..."
          bazel run --define APPLEID=$APPLEID --define APPLEID_PASSWORD=$APPLEID_PASSWORD --define APPLE_CODE_SIGNING_CERTIFICATE_URL=$APPLE_CODE_SIGNING_CERTIFICATE_URL --define APPLE_CODE_SIGNING_PASSWORD=$APPLE_CODE_SIGNING_PASSWORD --spawn_strategy=local //:deploy-github -- $CIRCLE_SHA1
          echo "Deploying to Homebrew..."
          export DEPLOY_BREW_TOKEN=$REPO_GITHUB_TOKEN DEPLOY_BREW_USERNAME=$REPO_GITHUB_USERNAME DEPLOY_BREW_EMAIL=$REPO_GITHUB_EMAIL
          bazel run --define version=$(cat VERSION) //:deploy-brew -- release

  deploy-windows:
    executor:
      name: win/default
      shell: cmd.exe
    working_directory: ~/typedb-workbase
    steps:
      - checkout
      - run: .circleci\windows\prepare.bat
      - run: .circleci\windows\deploy.bat
      - store_artifacts:
          path: bazel-bin\application-image.zip

workflows:
  release:
    jobs:
      - deploy-mac-and-brew:
          filters:
            branches:
              only: release-mac-windows
      - deploy-windows:
          filters:
            branches:
              only: release-mac-windows
